"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  QrCode,
  Plus,
  RotateCcw,
  X,
  AlertTriangle,
  Info,
} from "lucide-react";

import { FranchiseeOnly } from "@/components/RoleWrapper";
import {
  usePortalQRCodes,
  usePortalStations,
  useCreatePortalQRCode,
  useRegeneratePortalQRCode,
  useClosePortalQRCode,
} from "@/lib/queries/franchisee-portal";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface StationCharger {
  station_id: number;
  station_name: string;
  charger_id: number;
  charger_name: string;
  charge_point_string_id: string;
}

function QRCodesContent() {
  const { data: qrPayload, isLoading, error } = usePortalQRCodes();
  const { data: stations } = usePortalStations();

  const createMutation = useCreatePortalQRCode();
  const regenerateMutation = useRegeneratePortalQRCode();
  const closeMutation = useClosePortalQRCode();

  const [createOpen, setCreateOpen] = useState(false);
  const [selectedChargerId, setSelectedChargerId] = useState<string>("");

  const qrCodes = qrPayload?.data || [];
  const canCreateDirect = qrPayload?.can_create_direct ?? false;
  const razorpayStatus = qrPayload?.razorpay_account_status ?? null;

  // Build list of chargers without an active QR so the create dialog only
  // offers valid options.
  const availableChargers = useMemo<StationCharger[]>(() => {
    if (!stations) return [];
    const chargerIdsWithActiveQR = new Set(
      qrCodes.filter((q) => q.is_active).map((q) => q.charger_id)
    );
    const flat: StationCharger[] = [];
    for (const s of stations as any[]) {
      const chargers = s.chargers || [];
      for (const c of chargers) {
        if (chargerIdsWithActiveQR.has(c.id)) continue;
        flat.push({
          station_id: s.id,
          station_name: s.name || `Station ${s.id}`,
          charger_id: c.id,
          charger_name: c.name || c.charge_point_string_id,
          charge_point_string_id: c.charge_point_string_id,
        });
      }
    }
    return flat;
  }, [stations, qrCodes]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto" />
          <p className="text-muted-foreground mt-2">Loading QR codes...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-2">
            Failed to load QR codes
          </h2>
          <p className="text-gray-600">Please try refreshing the page.</p>
        </div>
      </div>
    );
  }

  const handleCreate = () => {
    if (!selectedChargerId) return;
    createMutation.mutate(Number(selectedChargerId), {
      onSuccess: () => {
        setCreateOpen(false);
        setSelectedChargerId("");
      },
    });
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-4">
        <h1 className="text-3xl font-bold">QR Codes</h1>
        <Dialog open={createOpen} onOpenChange={setCreateOpen}>
          <DialogTrigger asChild>
            <Button
              disabled={availableChargers.length === 0}
              title={
                availableChargers.length === 0
                  ? "All your chargers already have an active QR"
                  : "Create a QR code for one of your chargers"
              }
            >
              <Plus className="h-4 w-4 mr-2" />
              Create QR
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Create QR code</DialogTitle>
              <DialogDescription>
                Pick one of your chargers. The QR image is generated by
                Razorpay. The big label on the image shows{" "}
                {canCreateDirect ? (
                  <>
                    <span className="font-semibold">your business name</span>{" "}
                    because your Razorpay account is active.
                  </>
                ) : (
                  <>
                    <span className="font-semibold">VoltLync</span> until your
                    Razorpay account is activated. You can regenerate this QR
                    later to switch the label to your business.
                  </>
                )}
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-2">
              <label className="text-sm font-medium">Charger</label>
              <Select
                value={selectedChargerId}
                onValueChange={setSelectedChargerId}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select a charger" />
                </SelectTrigger>
                <SelectContent>
                  {availableChargers.map((c) => (
                    <SelectItem key={c.charger_id} value={String(c.charger_id)}>
                      {c.station_name} &middot; {c.charger_name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => {
                  setCreateOpen(false);
                  setSelectedChargerId("");
                }}
              >
                Cancel
              </Button>
              <Button
                onClick={handleCreate}
                disabled={!selectedChargerId || createMutation.isPending}
              >
                {createMutation.isPending ? "Creating…" : "Create QR"}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>

      {!canCreateDirect && (
        <Card className="border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-900/20">
          <CardContent className="pt-6">
            <div className="flex items-start gap-3">
              <AlertTriangle className="h-5 w-5 text-amber-600 mt-0.5 flex-shrink-0" />
              <div className="text-sm">
                <p className="font-semibold text-amber-900 dark:text-amber-100">
                  Razorpay account not active yet
                </p>
                <p className="text-amber-800 dark:text-amber-200 mt-1">
                  Until your KYC is complete, QR codes you create will display
                  <span className="font-semibold"> VoltLync</span> as the payee
                  on the customer's UPI app. Once your Razorpay account is
                  activated, come back here and click{" "}
                  <span className="font-semibold">Regenerate</span> on each QR
                  to switch the payee label to your business name (RBI
                  payer-payee transparency).
                </p>
                {razorpayStatus && (
                  <p className="text-xs text-amber-700 dark:text-amber-300 mt-2">
                    Current Razorpay status:{" "}
                    <span className="font-mono">{razorpayStatus}</span>
                  </p>
                )}
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {qrCodes.length === 0 ? (
        <Card>
          <CardContent className="py-12">
            <div className="text-center text-muted-foreground">
              <QrCode className="h-12 w-12 mx-auto mb-4 opacity-50" />
              <p>No QR codes yet.</p>
              <p className="text-xs mt-1">
                Click "Create QR" above to generate one for a charger.
              </p>
            </div>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {qrCodes.map((qr) => (
            <Card key={qr.id}>
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between gap-2">
                  <CardTitle className="text-base truncate">
                    {qr.charger_name || "Unknown Charger"}
                  </CardTitle>
                  <div className="flex gap-1 flex-shrink-0">
                    <Badge
                      variant={qr.is_active ? "default" : "destructive"}
                      className="text-xs"
                    >
                      {qr.is_active ? "Active" : "Inactive"}
                    </Badge>
                    <Badge
                      variant={qr.owner === "franchisee" ? "default" : "secondary"}
                      className="text-xs"
                      title={
                        qr.owner === "franchisee"
                          ? "QR image displays your business name"
                          : "QR image displays VoltLync (regenerate once Razorpay is active)"
                      }
                    >
                      {qr.owner === "franchisee" ? "Yours" : "Platform"}
                    </Badge>
                  </div>
                </div>
                <p className="text-xs text-muted-foreground">
                  Payee on QR: <span className="font-medium">{qr.payee_display_name}</span>
                </p>
              </CardHeader>
              <CardContent className="space-y-3">
                {qr.image_url && (
                  <div className="flex justify-center">
                    <img
                      src={qr.image_url}
                      alt={`QR code for ${qr.charger_name}`}
                      className="w-40 h-40 object-contain border rounded"
                    />
                  </div>
                )}
                <div className="text-xs text-muted-foreground space-y-1">
                  <p>
                    <span className="font-medium text-foreground">QR ID:</span>{" "}
                    <span className="font-mono">{qr.razorpay_qr_code_id}</span>
                  </p>
                  <p>
                    <span className="font-medium text-foreground">Created:</span>{" "}
                    {new Date(qr.created_at).toLocaleDateString()}
                  </p>
                </div>
                <div className="flex gap-2 pt-2">
                  <Button
                    variant="outline"
                    size="sm"
                    className="flex-1"
                    onClick={() => regenerateMutation.mutate(qr.id)}
                    disabled={regenerateMutation.isPending}
                    title="Close this QR and create a new one with today's payee label"
                  >
                    <RotateCcw className="h-3.5 w-3.5 mr-1" />
                    Regenerate
                  </Button>
                  {qr.is_active && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        if (confirm("Close this QR code? Customers at the charger will no longer be able to scan it until you create a new one.")) {
                          closeMutation.mutate(qr.id);
                        }
                      }}
                      disabled={closeMutation.isPending}
                    >
                      <X className="h-3.5 w-3.5" />
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <div className="flex items-start gap-2 text-xs text-muted-foreground">
        <Info className="h-3.5 w-3.5 mt-0.5 flex-shrink-0" />
        <p>
          Regenerating closes the old QR on Razorpay and creates a new one.
          Print the new QR image for the charger — the old printed QR will
          stop accepting payments.
        </p>
      </div>
    </div>
  );
}

export default function QRCodesPage() {
  return (
    <FranchiseeOnly
      fallback={
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="text-center">
            <h2 className="text-2xl font-bold text-gray-900 mb-2">
              Access Denied
            </h2>
            <p className="text-gray-600 mb-4">
              You need franchisee privileges to access this page.
            </p>
            <Link href="/dashboard" className="text-blue-600 hover:text-blue-800">
              Go to Dashboard
            </Link>
          </div>
        </div>
      }
    >
      <QRCodesContent />
    </FranchiseeOnly>
  );
}
