from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        -- Drop the old global unique on invoice_number (replaced by scoped uniques below).
        -- Tortoise's `unique=True` produces Postgres-autogenerated `<table>_<col>_key`;
        -- older Aerich-managed envs may have the `uid_*` name instead.
        ALTER TABLE "gst_invoice" DROP CONSTRAINT IF EXISTS "gst_invoice_invoice_number_key";
        DROP INDEX IF EXISTS "gst_invoice_invoice_number_key";
        DROP INDEX IF EXISTS "uid_gst_invoice_invoice_77d653";

        -- New columns: nullable first so existing rows aren't blocked; backfilled
        -- by backend/scripts/backfill_gst_schema.py before tightening to NOT NULL.
        ALTER TABLE "gst_invoice" ADD "place_of_supply_state_code" VARCHAR(5);
        ALTER TABLE "gst_invoice" ADD "series" VARCHAR(10);
        ALTER TABLE "gst_invoice" ADD "financial_year" VARCHAR(10);
        ALTER TABLE "gst_invoice" ADD "gst_rate_percent" DECIMAL(5,2) NOT NULL DEFAULT 18;

        -- Inline backfill of series/financial_year from the invoice_number
        -- (format VL[/F{id}]/{SERIES}/{FYSHORT}/{SEQ}). Safe for empty tables.
        UPDATE "gst_invoice"
        SET "series" = CASE
                WHEN "invoice_number" LIKE '%/QR/%' THEN 'QR'
                WHEN "invoice_number" LIKE '%/WAL/%' THEN 'WAL'
                ELSE 'WAL'
            END
        WHERE "series" IS NULL;

        UPDATE "gst_invoice"
        SET "financial_year" = (
            SUBSTRING(SPLIT_PART("invoice_number", '/', -2) FROM 1 FOR 4)
            || '-'
            || SUBSTRING(SPLIT_PART("invoice_number", '/', -2) FROM 5 FOR 2)
        )
        WHERE "financial_year" IS NULL
          AND SPLIT_PART("invoice_number", '/', -2) ~ '^[0-9]{6}$';

        -- Fallback: any row that still has NULL financial_year gets the current FY.
        UPDATE "gst_invoice"
        SET "financial_year" = CASE
                WHEN EXTRACT(MONTH FROM "invoice_date") >= 4
                    THEN EXTRACT(YEAR FROM "invoice_date")::TEXT
                        || '-'
                        || RIGHT((EXTRACT(YEAR FROM "invoice_date") + 1)::TEXT, 2)
                ELSE (EXTRACT(YEAR FROM "invoice_date") - 1)::TEXT
                        || '-'
                        || RIGHT(EXTRACT(YEAR FROM "invoice_date")::TEXT, 2)
            END
        WHERE "financial_year" IS NULL;

        ALTER TABLE "gst_invoice" ALTER COLUMN "series" SET NOT NULL;
        ALTER TABLE "gst_invoice" ALTER COLUMN "series" SET DEFAULT 'WAL';
        ALTER TABLE "gst_invoice" ALTER COLUMN "financial_year" SET NOT NULL;

        -- Drop cancellation/refund-voucher columns (infrastructure was unused)
        ALTER TABLE "gst_invoice" DROP COLUMN "status";
        ALTER TABLE "gst_invoice" DROP COLUMN "refund_amount";
        ALTER TABLE "gst_invoice" DROP COLUMN "cancelled_at";
        ALTER TABLE "gst_invoice" DROP COLUMN "cancellation_reason";

        -- Correct HSN/SAC default (998749 → 996749)
        ALTER TABLE "gst_invoice" ALTER COLUMN "hsn_sac_code" SET DEFAULT '996749';

        -- Transaction snapshot of GST rate at billing
        ALTER TABLE "transaction" ADD "gst_rate_percent" DECIMAL(5,2) NOT NULL DEFAULT 18;

        -- Drop credit-note table (no rows, never used)
        DROP TABLE IF EXISTS "gst_credit_note";

        -- Scoped uniqueness: per-(franchisee, FY) for franchisee-owned, and a
        -- separate partial unique for VoltLync-owned (franchisee_id IS NULL)
        -- because Postgres treats NULL as distinct in regular UNIQUE indexes.
        CREATE UNIQUE INDEX IF NOT EXISTS "uid_gst_invoice_franchi_1ad4c8"
            ON "gst_invoice" ("franchisee_id", "financial_year", "invoice_number")
            WHERE "franchisee_id" IS NOT NULL;
        CREATE UNIQUE INDEX IF NOT EXISTS "uid_gst_invoice_voltlync_fy"
            ON "gst_invoice" ("financial_year", "invoice_number")
            WHERE "franchisee_id" IS NULL;

        -- Same fix for the counter table — its existing unique_together
        -- doesn't cover the NULL-franchisee case.
        CREATE UNIQUE INDEX IF NOT EXISTS "uid_gst_invoice_counter_voltlync"
            ON "gst_invoice_counter" ("series", "financial_year")
            WHERE "franchisee_id" IS NULL;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        DROP INDEX IF EXISTS "uid_gst_invoice_counter_voltlync";
        DROP INDEX IF EXISTS "uid_gst_invoice_voltlync_fy";
        DROP INDEX IF EXISTS "uid_gst_invoice_franchi_1ad4c8";
        CREATE TABLE IF NOT EXISTS "gst_credit_note" (
            "id" SERIAL NOT NULL PRIMARY KEY,
            "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "credit_note_number" VARCHAR(50) NOT NULL UNIQUE,
            "reason" VARCHAR(255) NOT NULL,
            "credit_amount" DECIMAL(10,2) NOT NULL,
            "cgst_amount" DECIMAL(10,2),
            "sgst_amount" DECIMAL(10,2),
            "igst_amount" DECIMAL(10,2),
            "issue_date" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            "pdf_url" VARCHAR(500),
            "franchisee_id" INT REFERENCES "franchisee" ("id") ON DELETE CASCADE,
            "original_invoice_id" INT NOT NULL REFERENCES "gst_invoice" ("id") ON DELETE CASCADE
        );
        ALTER TABLE "transaction" DROP COLUMN "gst_rate_percent";
        ALTER TABLE "gst_invoice" ALTER COLUMN "hsn_sac_code" SET DEFAULT '998749';
        ALTER TABLE "gst_invoice" ADD "status" VARCHAR(9) NOT NULL DEFAULT 'ISSUED';
        ALTER TABLE "gst_invoice" ADD "refund_amount" DECIMAL(10,2);
        ALTER TABLE "gst_invoice" ADD "cancelled_at" TIMESTAMPTZ;
        ALTER TABLE "gst_invoice" ADD "cancellation_reason" TEXT;
        ALTER TABLE "gst_invoice" DROP COLUMN "place_of_supply_state_code";
        ALTER TABLE "gst_invoice" DROP COLUMN "series";
        ALTER TABLE "gst_invoice" DROP COLUMN "financial_year";
        ALTER TABLE "gst_invoice" DROP COLUMN "gst_rate_percent";
        CREATE UNIQUE INDEX IF NOT EXISTS "uid_gst_invoice_invoice_77d653" ON "gst_invoice" ("invoice_number");"""
