from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        -- ----------------------------------------------------------------------
        -- Drop stored wallet.balance; balance becomes a SUM derivation
        -- over wallet_transaction. Five steps in one transaction:
        --   1. Normalise legacy CHARGE_DEDUCT sign so SUM is correct.
        --   2. Capture any pre-existing drift as explicit adjustment rows.
        --   3. Redeem migration 32's NOT VALID constraint to VALID.
        --   4. Covering index on wallet_transaction for the SUM read path.
        --   5. Drop wallet.balance.
        -- ----------------------------------------------------------------------
        -- The DO blocks emit NOTICE output (visible in `aerich upgrade`
        -- stdout) for the auto-heal counts so an operator can verify the
        -- migration absorbed the expected amount of drift before deciding
        -- to promote staging → prod.

        -- 1. Pre-migration CHARGE_DEDUCT rows were stored as negative amounts.
        --    For the SUM formula in WalletService.get_balance to be correct,
        --    every row must store the absolute amount; direction is carried
        --    entirely by `type`.
        DO $$
        DECLARE flipped_count INT;
        BEGIN
            UPDATE "wallet_transaction"
               SET amount = ABS(amount)
             WHERE type = 'CHARGE_DEDUCT' AND amount < 0;
            GET DIAGNOSTICS flipped_count = ROW_COUNT;
            RAISE NOTICE 'Migration 33 step 1: sign-normalised % CHARGE_DEDUCT row(s)', flipped_count;
        END $$;

        -- 2. For each wallet whose stored balance differs from the derived
        --    sum by >= 0.01, insert an adjustment row of the appropriate
        --    type so the derived balance after this migration matches the
        --    pre-migration stored balance.
        DO $$
        DECLARE adjustment_count INT;
        DECLARE adjustment_sum NUMERIC;
        BEGIN
            WITH inserted AS (
                INSERT INTO "wallet_transaction" (wallet_id, amount, type, description, payment_metadata, created_at)
                SELECT w.id,
                       ABS(w.balance - COALESCE(s.derived, 0)),
                       CASE WHEN w.balance > COALESCE(s.derived, 0) THEN 'TOP_UP' ELSE 'CHARGE_DEDUCT' END,
                       'Pre-ledger-migration drift correction (auto-generated by migration 33)',
                       CASE WHEN w.balance > COALESCE(s.derived, 0)
                            THEN '{"status": "COMPLETED", "adjustment": true}'::jsonb
                            ELSE '{"adjustment": true}'::jsonb
                       END,
                       NOW()
                  FROM "wallet" w
                  LEFT JOIN (
                      SELECT wallet_id,
                             COALESCE(
                                 SUM(CASE
                                     WHEN type = 'TOP_UP'
                                          AND payment_metadata->>'status' = 'COMPLETED'
                                          THEN amount
                                     WHEN type = 'CHARGE_DEDUCT'
                                          THEN -amount
                                     ELSE 0
                                 END), 0) AS derived
                        FROM "wallet_transaction"
                       GROUP BY wallet_id
                  ) s ON s.wallet_id = w.id
                 WHERE w.balance IS NOT NULL
                   AND ABS(w.balance - COALESCE(s.derived, 0)) >= 0.01
                RETURNING amount
            )
            SELECT COUNT(*), COALESCE(SUM(amount), 0) INTO adjustment_count, adjustment_sum FROM inserted;
            RAISE NOTICE 'Migration 33 step 2: wrote % drift-correction row(s), total absolute delta ₹%',
                adjustment_count, adjustment_sum;
        END $$;

        -- 3. History is now sign-consistent; redeem the CHECK constraint.
        ALTER TABLE "wallet_transaction"
          VALIDATE CONSTRAINT "wallet_transaction_amount_non_negative";

        -- 4. Covering index. (Migration 34 tightens this to plain (wallet_id)
        --    since payment_metadata heap visits make INCLUDE redundant.)
        CREATE INDEX IF NOT EXISTS "idx_wallet_txn_balance"
            ON "wallet_transaction" (wallet_id) INCLUDE (amount, type);

        -- 5. Drop the stored balance column. WalletService.get_balance is
        --    now the canonical balance read across the codebase.
        ALTER TABLE "wallet" DROP COLUMN "balance";"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        -- Best-effort rollback. Practical recovery should be from a DB
        -- snapshot taken before the upgrade. This rebuilds the stored
        -- balance from the log so the app can boot under the old code.
        ALTER TABLE "wallet" ADD COLUMN "balance" DECIMAL(10,2);

        UPDATE "wallet" w
           SET balance = COALESCE((
               SELECT SUM(CASE
                          WHEN type = 'TOP_UP'
                               AND payment_metadata->>'status' = 'COMPLETED'
                               THEN amount
                          WHEN type = 'CHARGE_DEDUCT'
                               THEN -amount
                          ELSE 0
                      END)
                 FROM "wallet_transaction"
                WHERE wallet_id = w.id
           ), 0);

        DROP INDEX IF EXISTS "idx_wallet_txn_balance";

        ALTER TABLE "wallet_transaction"
          DROP CONSTRAINT IF EXISTS "wallet_transaction_amount_non_negative";
        ALTER TABLE "wallet_transaction"
          ADD CONSTRAINT "wallet_transaction_amount_non_negative"
          CHECK (amount >= 0) NOT VALID;"""
