"""Added correlation column

Revision ID: 78e96e64480b
Revises: 1948704d6128
Create Date: 2025-05-31 11:28:37.259884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e96e64480b'
down_revision: Union[str, None] = '1948704d6128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('correlation_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'correlation_id')
    # ### end Alembic commands ###
