"""fixed log schema

Revision ID: b80523fbaa7b
Revises: ae8125edd9c3
Create Date: 2025-05-30 17:39:06.533316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80523fbaa7b'
down_revision: Union[str, None] = 'ae8125edd9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('connector_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'connector_id')
    # ### end Alembic commands ###
