"""fixed log schema removed connector id

Revision ID: efc5a8c50a94
Revises: b80523fbaa7b
Create Date: 2025-05-30 19:21:13.758051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc5a8c50a94'
down_revision: Union[str, None] = 'b80523fbaa7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'connector_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('connector_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
